// * Types defined here are not used currently

const texturePackerOptions = {
  format: 'string',
  data: 'string',
  'trim-sprite-names': 'boolean',
  'prepend-folder-name': 'boolean',
  texturepath: 'string',
  'classfile-file': 'string',
  'header-file': 'string',
  'texture-format': 'string',
  sheet: 'string',
  'png-opt-level': 'string',
  'dither-type': 'string',
  'alpha-handling': 'string',
  'jpg-quality': 'string',
  'webp-quality': 'string',
  'pvr-quality': 'string',
  'etc1-quality': 'string',
  'dxt-mode': 'string',
  'flip-pvr': 'boolean',
  'content-protection': 'string',
  'max-width': 'number',
  'max-height': 'number',
  width: 'number',
  height: 'number',
  'size-constraints': 'string',
  'force-squared': 'boolean',
  variant: 'string',
  'force-identical-layout': 'boolean',
  scale: 'number',
  'scale-mode': 'string',
  algorithm: 'string',
  'basic-order': 'string',
  'basic-sort-by': 'string',
  'maxrects-heuristics': 'string',
  'pack-mode': 'string',
  multipack: 'boolean',
  'enable-rotation': 'boolean',
  'disable-rotation': 'boolean',
  'disable-auto-alias': 'boolean',
  'trim-mode': 'number',
  'trim-margin': 'number',
  'trim-threshold': 'number',
  'tracer-tolerance': 'number',
  extrude: 'number',
  'border-padding': 'number',
  'shape-padding': 'number',
  'common-divisor-x': 'number',
  'common-divisor-y': 'number',
  'shape-debug': 'boolean',
}

module.exports = texturePackerOptions
